python "train_mc copy.py"\
    --model_name_or_path "hfl/chinese-roberta-wwm-ext"\
    --train_file "data/train.json"\
    --validation_file "data/valid.json"\
    --context_file "data/context.json"\
    --max_seq_length 512\
    --per_device_train_batch_size 1\
    --gradient_accumulation_steps 2\
    --num_train_epochs 1\
    --learning_rate 3e-5\
    --output_dir "output_mc/"\
